# Generated by Django 4.2.7 on 2023-12-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_mebel_options_mebel_parse_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mebel',
            options={'ordering': ['price', 'parse_date_time'], 'verbose_name': 'Мебель', 'verbose_name_plural': 'Мебель'},
        ),
        migrations.AlterField(
            model_name='mebel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
