# Generated by Django 4.1.7 on 2023-12-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_mebel_options_alter_mebel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mebel',
            options={'ordering': ['parse_date_time', '-price'], 'verbose_name': 'Мебель', 'verbose_name_plural': 'Мебель'},
        ),
    ]
